spring.application.name=trackingsystem
spring.datasource.url=jdbc:mysql://localhost:3306/parcel_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=9023
ors.api.key=cwxcHxXicaBBKaSkoxVde0GZ3CQC52FPnL3N06ftYUNhHNzqVuLth3rAc2DZ2rLX